framework:
    secret: '%env(APP_SECRET)%'
    form: ~
    csrf_protection: ~
    validation:
        mapping:
            paths: 
                - '%kernel.project_dir%/config/validation.xml'
    #http_method_override: true

    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true
    #assets:
    #    version: v1
