security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(error|profiler|wdt)|css|img|js)/
            security: false
        main:
            lazy: true


