framework:
    validation:
        email_validation_mode: html5
        mapping:
            paths:
                - '%kernel.project_dir%/config/validation/'

when@test:
    framework:
        validation:
            not_compromised_password: false
