version: '3.8'
services:
    database:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    php:
        build:
            context: config/docker/php-fpm
            args:
                HOST_UID: 1000
        volumes:
            - ./:/user/customize:delegated
            - $HOME/.bashrc:/user/.bashrc:delegated
            - $HOME/.composer/cache:/user/.composer/cache:delegated
            - $HOME/.gitignore:/user/.gitignore:delegated
            - $HOME/.ssh:/user/.ssh:delegated
            - $HOME/.vimrc:/user/.vimrc:delegated
        working_dir: /user/customize
        ports:
            - "9000:9000"
        links:
            - database
        environment:
            - PATH=./bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - COLUMNS=190
            - LINES=42
            - APP_ENV=dev
            - APP_DEBUG=1
            - APP_DATABASE_URL=mysql://root:root@database/customize
            - APP_TEST_DATABASE_URL=mysql://root:root@database/customize_test
            - APP_MAILER_URL=null://127.0.0.1
            - APP_SECRET=ThisIsNotReallySecretButOK
    nginx:
        build: config/docker/nginx
        ports:
            - "8080:80"
        links:
            - php
        volumes:
            - ./:/user/customize

