services:
    _defaults:
        public: true
        autowire: true

    # uncomment after having created at least one fixture
    #Tests\Fixtures\:
    #    resource: '../tests/Fixtures/*'
    #    tags: ['doctrine.fixture.orm']

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'

