services:
    _defaults:
        autowire: true
        autoconfigure: true

    Infrastructure\:
        resource: '../src/Infrastructure'
        exclude: '../src/Infrastructure/{Kernel.php,Security/User/User.php}'

    Presentation\:
        resource: '../src/Presentation'

    #Application\Handler\:
    #    resource: '../src/Application/Handler'
    #    exclude: '../src/Application/Handler/*/Abstract*'
    #    tags: ['messenger.message_handler']

