parameters:
    locale: en

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
