parameters:
    locale: en
    domain: '%env(APP_DOMAIN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php}'

