services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/App/*'
        exclude: '../src/App/{File,Kernel.php,Security/User/User.php}'

    Beelab\Handler\:
        resource: '../src/Beelab/Handler'
        exclude: '../src/Beelab/Handler/*/Abstract*'
        public: true
        tags: ['command_handler']

